### ISSUE TITLE
No logrotate

### ISSUE THREAD

**Issue by auanasgheps** [OpenMediaVault-Plugin-Developers/openmediavault-wakealarm#10]
Today by looking at `/var/log/` I've discovered that the biggest file is `wakealarm.log` and the first event dates back when I installed the plugin. 
Can you please add logrotate configuration for wakealarm? 

These log does not have any use to user (I actually [disabled ](https://forum.openmediavault.org/index.php?thread/24137-wakealarm-spamming-error-in-syslog/&postID=231489#post231489)their appearance in syslog) and would be nice to keep the size to a minimum.

I would actually create a PR but I'm not an expert with logrotate.

Untested, but maybe something on the lines of:

/etc/logrotate.d/openmediavault-wakealarm
```
/var/log/wakealarm.log {
  rotate 4
  copytruncate
  weekly
  compress
  missingok
  notifempty
}
```

**Comment by ryecoaaron** [comment]
I added the file - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-wakealarm/commit/302b86ae4ff93a23ededddd972460603a77db97a

I will push out a new package later.

**Comment by auanasgheps** [comment]
Kind reminder :)

**Comment by ryecoaaron** [comment]
5.0.2 in the repo now.
