### ISSUE TITLE
Only wakes once

### ISSUE THREAD

**Issue by pikim** [OpenMediaVault-Plugin-Developers/openmediavault-wakealarm#5]
I'm running OMV Arrakis together with the autoshutdown and wakealarm plugins. The basic idea is to let autoshutdown do it's work and let wakealarm wake th PC at a later time.

The sequence works exactly once:
1. start the NAS manually
2. shut PC down by autoshutdown
3. wake PC by wakealarm
4. shut PC down by autoshutdown
5. PC doesn't wake up again

`date -d @$(cat /sys/class/rtc/rtc0/wakealarm)` always shows the desired time, but anything seems to happen that causes wakealarm to fail. Setting the time with `rtcwake` always works.

**Comment by ryecoaaron** [comment]
closing due to age.
