### ISSUE TITLE
Getting Exception when using /usr/sbin/wakealarm directly

### ISSUE THREAD

**Issue by erdnussflips** [OpenMediaVault-Plugin-Developers/openmediavault-wakealarm#7]
When I update my system or using wakealarm directly the wakealarm script raises the following exception:

> Traceback (most recent call last):
  File "/usr/sbin/wakealarm", line 141, in <module>
    main()
  File "/usr/sbin/wakealarm", line 137, in main
    wakealarm.get_next_alarm()
  File "/usr/sbin/wakealarm", line 88, in get_next_alarm
    next_alarm = min(times)
ValueError: min() arg is an empty sequence

OMV: 4.1.9
Python: 2.7.13
Debian: 9.5

**Comment by ErdnussFlipS** [comment]
Ok, that was a misinterpretation. It has nothing to do with a system update.

**Comment by ryecoaaron** [comment]
Closing due to age.
