### ISSUE TITLE
Wakealarm log every minute, is it normal?

### ISSUE THREAD

**Issue by Ansem93** [OpenMediaVault-Plugin-Developers/openmediavault-wakealarm#8]
Hi, I noticed right now that every minute I have this log:
Sep 10 00:19:01 delibird CRON[27128]: (root) CMD (   test -x /usr/sbin/wakealarm && /usr/sbin/wakealarm > /dev/null 2>&1)
Sep 10 00:20:01 delibird CRON[27168]: (root) CMD (   test -x /usr/sbin/wakealarm && /usr/sbin/wakealarm > /dev/null 2>&1)
Sep 10 00:21:01 delibird CRON[27206]: (root) CMD (   test -x /usr/sbin/wakealarm && /usr/sbin/wakealarm > /dev/null 2>&1)

How can I avoid it?

**Comment by ryecoaaron** [comment]
The plugin installs a cron job that runs wakealarm every minute and cron logs when it runs.  Not sure how to change that but it shouldn't cause a problem.

**Comment by Ansem93** [comment]
Thanks for the advice. There is no way to have wakealarm write in a dedicated file instead of syslog?

**Comment by ryecoaaron** [comment]
wakealarm does write to a dedicated file - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-wakealarm/blob/master/etc/rsyslog.d/wakealarm.conf

cron is logging to syslog each time it executes the cron job.  I don't know of a good way to stop this without stopping all logging of cron jobs.

**Comment by votdev** [comment]
Maybe this helps: https://serverfault.com/a/512356

**Comment by votdev** [comment]
And yes, this output is normal.

**Comment by Ansem93** [comment]
ooops. Forgot to answer at this! Yes, I solved creating a dedicated log file for cron adding this line to /etc/rsyslog.conf :
cron.*                          /var/log/cron.log

Is it possible to update this uplugin so that it will do it by default?
