### ISSUE TITLE
sys log error

### ISSUE THREAD

**Issue by yfdoor** [OpenMediaVault-Plugin-Developers/openmediavault-wakealarm#9]
This log appears every one minute in system log, so if it's a error? I have removed all 
“Planning tasks” and reboot OMV system.

sys Log:
`Apr 3 20:40:01 omv CRON[25633]: (root) CMD ( test -x /usr/sbin/wakealarm && /usr/sbin/wakealarm > /dev/null 2>&1) 
Apr 3 20:41:01 omv CRON[25646]: (root) CMD ( test -x /usr/sbin/wakealarm && /usr/sbin/wakealarm > /dev/null 2>&1) 
Apr 3 20:42:01 omv CRON[25657]: (root) CMD ( test -x /usr/sbin/wakealarm && /usr/sbin/wakealarm > /dev/null 2>&1) 
Apr 3 20:43:01 omv CRON[25687]: (root) CMD ( test -x /usr/sbin/wakealarm && /usr/sbin/wakealarm > /dev/null 2>&1) 
Apr 3 20:44:01 omv CRON[25698]: (root) CMD ( test -x /usr/sbin/wakealarm && /usr/sbin/wakealarm > /dev/null 2>&1) 
Apr 3 20:45:01 omv CRON[25715]: (root) CMD (/usr/sbin/omv-mkrrdgraph >/dev/null 2>&1) 
Apr 3 20:45:01 omv CRON[25714]: (root) CMD ( test -x /usr/sbin/wakealarm && /usr/sbin/wakealarm > /dev/null 2>&1) 
Apr 3 20:46:01 omv CRON[25832]: (root) CMD ( test -x /usr/sbin/wakealarm && /usr/sbin/wakealarm > /dev/null 2>&1)`

OMV Versions
5.3.9

**Comment by votdev** [comment]
According to https://github.com/openmediavault/openmediavault/issues/663#issuecomment-608443214 this can be closed IMO.

**Comment by ryecoaaron** [comment]
https://forum.openmediavault.org/index.php?thread/24137-wakealarm-spamming-error-in-syslog/&postID=231489&highlight=wakealarm#post231489
